using Astrobank.Application.Interfaces.Repositories;
using Astrobank.Domain.Users;
using Microsoft.AspNetCore.Identity;

namespace Astrobank.Infrastructure.Identity;

public class AstrobankUserStore :
    IUserStore<User>,
    IUserPasswordStore<User>,
    IUserEmailStore<User>,
    IUserRoleStore<User>
{
    private readonly IUserRepository _userRepository;
    private readonly IRoleRepository _roleRepository;

    public AstrobankUserStore(IUserRepository userRepository, IRoleRepository roleRepository)
    {
        _userRepository = userRepository;
        _roleRepository = roleRepository;
    }

    public void Dispose()
    {
        // No unmanaged resources to dispose
    }

    // --- IUserStore<User> ---

    public Task<string> GetUserIdAsync(User user, CancellationToken cancellationToken)
    {
        return Task.FromResult(user.UserID.ToString());
    }

    public Task<string?> GetUserNameAsync(User user, CancellationToken cancellationToken)
    {
        return Task.FromResult(user.Username)!;
    }

    public Task SetUserNameAsync(User user, string? userName, CancellationToken cancellationToken)
    {
        // We use required modifier for Username, so this shouldn't technically be null, but interface allows it.
        if (userName != null)
        {
            // Reflection used here since it's `init` in Domain.
            // In a real scenario with strict DDD, we'd have a `user.SetUsername(userName)` method.
            typeof(User).GetProperty(nameof(User.Username))!.SetValue(user, userName);
        }
        return Task.CompletedTask;
    }

    public Task<string?> GetNormalizedUserNameAsync(User user, CancellationToken cancellationToken)
    {
        return Task.FromResult(user.Username.ToUpperInvariant())!;
    }

    public Task SetNormalizedUserNameAsync(User user, string? normalizedName, CancellationToken cancellationToken)
    {
        // Astrobank doesn't store NormalizedUsername explicitly, so we just ignore this.
        return Task.CompletedTask;
    }

    public async Task<IdentityResult> CreateAsync(User user, CancellationToken cancellationToken)
    {
        await _userRepository.AddAsync(user, cancellationToken);
        return IdentityResult.Success;
    }

    public async Task<IdentityResult> UpdateAsync(User user, CancellationToken cancellationToken)
    {
        await _userRepository.UpdateAsync(user, cancellationToken);
        return IdentityResult.Success;
    }

    public async Task<IdentityResult> DeleteAsync(User user, CancellationToken cancellationToken)
    {
        await _userRepository.DeleteAsync(user, cancellationToken);
        return IdentityResult.Success;
    }

    public async Task<User?> FindByIdAsync(string userId, CancellationToken cancellationToken)
    {
        if (int.TryParse(userId, out int id))
        {
            return await _userRepository.GetByIdAsync(id, cancellationToken);
        }
        return null;
    }

    public async Task<User?> FindByNameAsync(string normalizedUserName, CancellationToken cancellationToken)
    {
        // Our domain doesn't store normalized name, assuming we do case-insensitive match on Username in DB
        // The EF Core query generated by GetByUsernameAsync will be case-insensitive by default in SQL Server.
        return await _userRepository.GetByUsernameAsync(normalizedUserName, cancellationToken);
    }


    // --- IUserPasswordStore<User> ---

    public Task SetPasswordHashAsync(User user, string? passwordHash, CancellationToken cancellationToken)
    {
        if (passwordHash != null)
        {
            // Reflection because it's `init` or `private set` in Domain.
            typeof(User).GetProperty(nameof(User.PasswordHash))!.SetValue(user, passwordHash);
        }
        return Task.CompletedTask;
    }

    public Task<string?> GetPasswordHashAsync(User user, CancellationToken cancellationToken)
    {
        return Task.FromResult(user.PasswordHash)!;
    }

    public Task<bool> HasPasswordAsync(User user, CancellationToken cancellationToken)
    {
        return Task.FromResult(!string.IsNullOrEmpty(user.PasswordHash));
    }


    // --- IUserEmailStore<User> ---

    public Task SetEmailAsync(User user, string? email, CancellationToken cancellationToken)
    {
        if (email != null)
        {
            typeof(User).GetProperty(nameof(User.Email))!.SetValue(user, email);
        }
        return Task.CompletedTask;
    }

    public Task<string?> GetEmailAsync(User user, CancellationToken cancellationToken)
    {
        return Task.FromResult(user.Email)!;
    }

    public Task<bool> GetEmailConfirmedAsync(User user, CancellationToken cancellationToken)
    {
        // Astrobank user doesn't have EmailConfirmed. We assume true or tie it to Status.
        return Task.FromResult(true);
    }

    public Task SetEmailConfirmedAsync(User user, bool confirmed, CancellationToken cancellationToken)
    {
        // Not implemented in Astrobank POCO.
        return Task.CompletedTask;
    }

    public async Task<User?> FindByEmailAsync(string normalizedEmail, CancellationToken cancellationToken)
    {
        return await _userRepository.GetByEmailAsync(normalizedEmail, cancellationToken);
    }

    public Task<string?> GetNormalizedEmailAsync(User user, CancellationToken cancellationToken)
    {
        return Task.FromResult(user.Email.ToUpperInvariant())!;
    }

    public Task SetNormalizedEmailAsync(User user, string? normalizedEmail, CancellationToken cancellationToken)
    {
        return Task.CompletedTask;
    }


    // --- IUserRoleStore<User> ---

    public async Task AddToRoleAsync(User user, string roleName, CancellationToken cancellationToken)
    {
        var role = await _roleRepository.GetByNameAsync(roleName, cancellationToken);
        if (role != null)
        {
            typeof(User).GetProperty(nameof(User.RoleID))!.SetValue(user, role.RoleID);
        }
    }

    public Task RemoveFromRoleAsync(User user, string roleName, CancellationToken cancellationToken)
    {
        // Astrobank only supports one role. Removing a role would mean assigning a default or nulling it.
        // As per frozen schema, RoleID is required (int, not int?). So we cannot remove it.
        throw new NotSupportedException("Astrobank requires a user to always have a single Role.");
    }

    public async Task<IList<string>> GetRolesAsync(User user, CancellationToken cancellationToken)
    {
        if (user.Role != null)
        {
            return new List<string> { user.Role.Name };
        }

        var role = await _roleRepository.GetByIdAsync(user.RoleID, cancellationToken);
        return role != null ? new List<string> { role.Name } : new List<string>();
    }

    public async Task<bool> IsInRoleAsync(User user, string roleName, CancellationToken cancellationToken)
    {
        var roles = await GetRolesAsync(user, cancellationToken);
        return roles.Contains(roleName, StringComparer.OrdinalIgnoreCase);
    }

    public Task<IList<User>> GetUsersInRoleAsync(string roleName, CancellationToken cancellationToken)
    {
        // Implementing this would require a specific repository method.
        // For standard Identity flow, it's rarely used directly, throwing NotSupported for now.
        throw new NotSupportedException();
    }
}
